import { Student } from "../types";

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stud_1",
    name: "Diego Alexander Guevara Cruz",
    belt: "Cinta Verde",
    birthDate: "2010-04-12",
    phone: "7123-4567",
    email: "diego.guevara@mail.com",
    address: "Colonia el Sitio, Pasaje 3, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Alexander Guevara Sr.",
    emergencyContactPhone: "7890-1234",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-02-15"
  },
  {
    id: "stud_2",
    name: "Josia Audiel Zelaya Torres",
    belt: "Cinta Amarilla",
    birthDate: "2012-08-22",
    phone: "7214-5896",
    email: "josia.zelaya@mail.com",
    address: "Urbanización Jardines del Río, San Miguel",
    bloodType: "A+",
    allergies: "Polvo",
    medications: "Ninguno",
    chronicConditions: "Asma controlada",
    emergencyContactName: "Patricia Torres",
    emergencyContactPhone: "6124-7856",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-03-01"
  },
  {
    id: "stud_3",
    name: "Somer Betsabé Segovia Lazo",
    belt: "Cinta Verde",
    birthDate: "2011-05-18",
    phone: "7022-3344",
    email: "somer.segovia@mail.com",
    address: "Barrio El Centro, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Betsabé Lazo",
    emergencyContactPhone: "7011-2233",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-01-20"
  },
  {
    id: "stud_4",
    name: "Zabdi Sismaí Segovia Lazo",
    belt: "Cinta Verde",
    birthDate: "2013-11-02",
    phone: "7022-3344",
    email: "zabdi.segovia@mail.com",
    address: "Barrio El Centro, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Betsabé Lazo",
    emergencyContactPhone: "7011-2233",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-01-20"
  },
  {
    id: "stud_5",
    name: "Darwin José Cinta Naranja",
    belt: "Cinta Naranja",
    birthDate: "2009-07-07",
    phone: "7488-9900",
    email: "darwin.jose@mail.com",
    address: "Colonia Milagro de la Paz, San Miguel",
    bloodType: "A-",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "José Alvarenga",
    emergencyContactPhone: "7322-1100",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-04-12"
  },
  {
    id: "stud_6",
    name: "Betzy Elisabeth Pleitez",
    belt: "Cinta Naranja",
    birthDate: "2012-10-15",
    phone: "7911-3344",
    email: "betzy.pleitez@mail.com",
    address: "Residencial Barcelona, San Miguel",
    bloodType: "B+",
    allergies: "Penicilina",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Elisabeth de Pleitez",
    emergencyContactPhone: "7611-3399",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-04-15"
  },
  {
    id: "stud_7",
    name: "Francisca Arias Torres",
    belt: "Cinta Amarilla",
    birthDate: "2014-01-30",
    phone: "7344-5566",
    email: "francisca.arias@mail.com",
    address: "Colonia Kury, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Francisco Arias",
    emergencyContactPhone: "7299-8877",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-05-10"
  },
  {
    id: "stud_8",
    name: "Estefany Saraí Arias",
    belt: "Cinta Amarilla",
    birthDate: "2011-12-05",
    phone: "7344-5566",
    email: "estefany.arias@mail.com",
    address: "Colonia Kury, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Francisco Arias",
    emergencyContactPhone: "7299-8877",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-05-10"
  },
  {
    id: "stud_9",
    name: "Daniel Alejandro Portillo Vásquez",
    belt: "Cinta Verde",
    birthDate: "2010-09-14",
    phone: "7555-8822",
    email: "daniel.portillo@mail.com",
    address: "Caserío El Tablón, San Miguel",
    bloodType: "AB+",
    allergies: "Mariscos",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Alejandro Portillo",
    emergencyContactPhone: "7022-8822",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-02-18"
  },
  {
    id: "stud_10",
    name: "Manuel Eliasib Hernández Majano",
    belt: "Cinta Amarilla",
    birthDate: "2013-03-25",
    phone: "7233-0099",
    email: "manuel.hernandez@mail.com",
    address: "Colonia Ciudad Real, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Eliasib Hernández",
    emergencyContactPhone: "7122-3344",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-03-10"
  },
  {
    id: "stud_11",
    name: "Madai Martínez",
    belt: "Participante",
    birthDate: "2015-06-18",
    phone: "7900-1122",
    email: "madai.martinez@mail.com",
    address: "Barrio San Felipe, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Madai de Martínez",
    emergencyContactPhone: "7900-2211",
    mediaConsent: true,
    medicalConsent: false,
    waiverConsent: true,
    registrationDate: "2024-06-01"
  },
  {
    id: "stud_12",
    name: "Zabdiel Majano Santos",
    belt: "Cinta Amarilla",
    birthDate: "2012-02-10",
    phone: "7088-3322",
    email: "zabdiel.majano@mail.com",
    address: "Colonia Satélite, San Miguel",
    bloodType: "B+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Santos Majano",
    emergencyContactPhone: "7188-4433",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-03-12"
  },
  {
    id: "stud_13",
    name: "Jehún Abisai Amaya González",
    belt: "Cinta Morada",
    birthDate: "2008-01-20",
    phone: "7611-2288",
    email: "jehun.amaya@mail.com",
    address: "Colonia Panamericana, San Miguel",
    bloodType: "O+",
    allergies: "Ácaros",
    medications: "Ninguno",
    chronicConditions: "Rinitis alérgica",
    emergencyContactName: "Abisai Amaya",
    emergencyContactPhone: "7611-3388",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2023-09-15"
  },
  {
    id: "stud_14",
    name: "Zabdiel Atli Majano Santos",
    belt: "Cinta Amarilla",
    birthDate: "2014-07-04",
    phone: "7088-3322",
    email: "zabdiel.atli@mail.com",
    address: "Colonia Satélite, San Miguel",
    bloodType: "B+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Santos Majano",
    emergencyContactPhone: "7188-4433",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-03-12"
  },
  {
    id: "stud_15",
    name: "Kinberlyn Nahomy Ramírez Ortiz",
    belt: "Participante",
    birthDate: "2015-05-12",
    phone: "7400-5511",
    email: "kinberlyn.ramirez@mail.com",
    address: "Canton El Niño, El Salvador, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Rosa Ortiz",
    emergencyContactPhone: "7400-5522",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-10"
  },
  {
    id: "stud_16",
    name: "Ana Patricia García Chicas",
    belt: "Participante",
    birthDate: "2011-03-14",
    phone: "7322-9900",
    email: "ana.garcia@mail.com",
    address: "Caserío Los Espinos, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Patricia Chicas",
    emergencyContactPhone: "7322-9911",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-05-20"
  },
  {
    id: "stud_17",
    name: "Juan David García Chicas",
    belt: "Participante",
    birthDate: "2013-09-09",
    phone: "7322-9900",
    email: "juan.garcia@mail.com",
    address: "Caserío Los Espinos, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Patricia Chicas",
    emergencyContactPhone: "7322-9911",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-05-20"
  },
  {
    id: "stud_18",
    name: "Patricia Chicas",
    belt: "Participante",
    birthDate: "1988-12-05",
    phone: "7322-9911",
    email: "patricia.chicas@mail.com",
    address: "Caserío Los Espinos, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Manuel García",
    emergencyContactPhone: "7122-3344",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-05-20"
  },
  {
    id: "stud_19",
    name: "Carlos Alejandro Amaya Gámez",
    belt: "Cinta Verde",
    birthDate: "2009-08-11",
    phone: "7844-3311",
    email: "carlos.amaya@mail.com",
    address: "Urbanización Las Brisas, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Carlos Amaya Sr.",
    emergencyContactPhone: "7844-3322",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-01-15"
  },
  {
    id: "stud_20",
    name: "Hasem Abisai Reyes",
    belt: "Participante",
    birthDate: "2016-01-15",
    phone: "7011-5588",
    email: "hasem.reyes@mail.com",
    address: "Colonia Belén, San Miguel",
    bloodType: "O+",
    allergies: "Frutos secos",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Abisai Reyes",
    emergencyContactPhone: "7011-5599",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-15"
  },
  {
    id: "stud_21",
    name: "Jezreel Atlai Lazo Majano",
    belt: "Cinta Verde-Morada",
    birthDate: "2010-02-28",
    phone: "7111-9922",
    email: "jezreel.lazo@mail.com",
    address: "Avenida Roosevelt Sur, San Miguel",
    bloodType: "B-",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Evelyn Majano",
    emergencyContactPhone: "7111-9933",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2023-11-10"
  },
  {
    id: "stud_22",
    name: "Jafet Abisai Lazo Majano",
    belt: "Cinta Verde-Morada",
    birthDate: "2012-06-04",
    phone: "7111-9922",
    email: "jafet.lazo@mail.com",
    address: "Avenida Roosevelt Sur, San Miguel",
    bloodType: "B-",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Evelyn Majano",
    emergencyContactPhone: "7111-9933",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2023-11-10"
  },
  {
    id: "stud_23",
    name: "Daniel Abisai Lazo Isaguirre",
    belt: "Participante",
    birthDate: "2015-09-18",
    phone: "7444-2200",
    email: "daniel.isaguirre@mail.com",
    address: "Caserío El Jocote, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Abisai Lazo",
    emergencyContactPhone: "7444-2211",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-05"
  },
  {
    id: "stud_24",
    name: "Génesis Naara Lazo Ramírez",
    belt: "Participante",
    birthDate: "2016-04-04",
    phone: "7555-0011",
    email: "genesis.lazo@mail.com",
    address: "Colonia Milagro de la Paz, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Naara Ramírez",
    emergencyContactPhone: "7555-0022",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-08"
  },
  {
    id: "stud_25",
    name: "Jonathan Zabdiel Lazo Ramírez",
    belt: "Participante",
    birthDate: "2014-11-12",
    phone: "7555-0011",
    email: "jonathan.lazo@mail.com",
    address: "Colonia Milagro de la Paz, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Naara Ramírez",
    emergencyContactPhone: "7555-0022",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-08"
  },
  {
    id: "stud_26",
    name: "Joab Benjamín Lazo Ramírez",
    belt: "Participante",
    birthDate: "2013-05-24",
    phone: "7555-0011",
    email: "joab.lazo@mail.com",
    address: "Colonia Milagro de la Paz, San Miguel",
    bloodType: "A+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Naara Ramírez",
    emergencyContactPhone: "7555-0022",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-06-08"
  },
  {
    id: "stud_27",
    name: "Zulma Araceli Benítez De Perlas",
    belt: "Cinta Naranja",
    birthDate: "1985-07-14",
    phone: "7200-8800",
    email: "zulma.benitez@mail.com",
    address: "Residencial San Francisco, San Miguel",
    bloodType: "AB-",
    allergies: "Picaduras de insectos",
    medications: "Loratadina (si es necesario)",
    chronicConditions: "Alergias crónicas",
    emergencyContactName: "Salvador Perlas",
    emergencyContactPhone: "7200-8855",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-04-10"
  },
  {
    id: "stud_28",
    name: "Yudy Guadalupe Alvarado Benítez",
    belt: "Cinta Naranja",
    birthDate: "2010-12-18",
    phone: "7311-2299",
    email: "yudy.alvarado@mail.com",
    address: "Colonia Gavidia, San Miguel",
    bloodType: "O+",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Guadalupe de Alvarado",
    emergencyContactPhone: "7311-2244",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-04-14"
  },
  {
    id: "stud_29",
    name: "Salvador Joaquín Villatoro Benítez",
    belt: "Cinta Naranja",
    birthDate: "2012-01-28",
    phone: "7822-4466",
    email: "salvador.villatoro@mail.com",
    address: "Colonia San Joaquín, San Miguel",
    bloodType: "O-",
    allergies: "Ninguna",
    medications: "Ninguno",
    chronicConditions: "Ninguna",
    emergencyContactName: "Joaquín Villatoro",
    emergencyContactPhone: "7822-4411",
    mediaConsent: true,
    medicalConsent: true,
    waiverConsent: true,
    registrationDate: "2024-04-18"
  }
];
